version: '3'

services:
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  api:
    container_name: backend
    build: api/
    image: backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - 3000:3000
  front:
    container_name: frontend
    build: front/
    image: frontend
    command: npm run dev
    env_file:
      - ./front/.env
    volumes:
      - ./front:/app
    ports:
      # コンテナ複数起動のため範囲指定
      - 8080-8081:8080
    depends_on:
      - api
volumes:
  mysql-data:
