version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.2-node
        environment:
          BUNDLER_VERSION: 2.2.22
    steps:
      - checkout
      - ruby/install-deps

  test:
    parallelism: 3
    docker:
      - image: circleci/ruby:3.0.2-node
        environment:
          RAILS_ENV: test
          BUNDLER_VERSION: 2.2.22
          # - RAILS_ENV: 'test'
          # - BUNDLER_VERSION: 2.2.22
      - image: circleci/mysql:8.0.27
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_ROOT_HOST: '%'
          # MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          # - MYSQL_ROOT_HOST: '%'
    # working_directory: ~/repo
    steps:
      - checkout
      - ruby/install-deps
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "Gemfile.lock" }}
      #       - v1-dependencies-
      # - run:
      #     name: install dependencies
      #     command: |
      #       gem install bundler -v 2.2.22
      #       bundle install --jobs=4 --retry=3 --path vendor/bundle
      # - save_cache:
      #     paths:
      #       - ./vendor/bundle
      #     key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: mv config/database.yml.ci config/database.yml
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - ruby/rspec-test
      - ruby/rubocop-check
      # - run:
      #     name: run tests
      #     command: |
      #       mkdir /tmp/test-results
      #       TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
      #         circleci tests split --split-by=timings)"
      #       bundle exec rspec \
      #         --format progress \
      #         --format RspecJunitFormatter \
      #         --out /tmp/test-results/rspec.xml \
      #         --format progress \
      #         $TEST_FILES
      # - store_test_results:
      #     path: /tmp/test-results
      # - store_artifacts:
      #     path: /tmp/test-results
      #     destination: test-results

#   deploy:
#     docker:
#       - image: circleci/ruby:3.0.2-node
#         environment:
#           - BUNDLER_VERSION: 2.2.22
#     steps:
#       - checkout
#       # - ruby/install-deps #orb必要そう
#       - add_ssh_keys:
#           fingerprints:
#             - "ff:66:c2:9b:5d:88:a5:c2:26:58:8b:75:fc:4a:4f:84"
#       - deploy:
#           name: Capistrano deploy
#           command: bundle exec cap production deploy

workflows:
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master