default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: db
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: portfolio_app_development

test:
  <<: *default
  database: portfolio_app_test

production:
  <<: *default
  database: portfolio_app_production
  username: yusuke
  password: <%= Rails.application.credentials.dig(:db, :password) %>
  host: <%= Rails.application.credentials.dig(:db, :endpoint) %>
  socket: /var/lib/mysql/mysql.sock #AWSのため