default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: portfolio_app_development

test:
  <<: *default
  database: portfolio_app_test


production:
  <<: *default
  # aws用 これでDocker使えたら下の削除予定
  # database: portfolio_app_production
  database: pf_production
  username: <%= ENV['USER_NAME'] %>
  password: <%= ENV['DB_PASSWORD'] %> #defaultと同じなので削除予定
  host: <%= ENV['ENDPOINT'] %>
  socket: /var/lib/mysql/mysql.sock

# docker用
  # database: portfolio_app_production
  # username: <%= ENV['USER_NAME'] %>
  # password: <%= ENV['DB_PASSWORD'] %>
  # host: <%= ENV['ENDPOINT'] %>
  # socket: /var/lib/mysql/mysql.sock