default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  host: db
  database: portfolio_app_development

test:
  <<: *default
  host: <%= ENV['DB_HOST'] || 'db' %>
  database: portfolio_app_test

production:
  <<: *default

  # ECS用
  database: pf_production
  url: <%= ENV['DATABASE_URL'] %>